

repositories:
  - cms.cern.ch
  - sft.cern.ch
  - grid.cern.ch
  - ilc.desy.de
  - nova.opensciencegrid.org
  

prefetcher:
  enabled: true
  jobs:
    cat_readme:
      command: 'cat /cvmfs/sft.cern.ch/README.md'
#      user: 'root'
#      minute: '*'
#      hour: '*'
#      day: '*'
#      month: '*'
      weekday: '6'

